# Generated by Django 4.1.3 on 2024-12-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpioneer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcard',
            old_name='name',
            new_name='product_name',
        ),
    ]
