# Generated by Django 4.1.3 on 2024-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpioneer', '0002_rename_name_productcard_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productcard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
