# Generated by Django 4.1.3 on 2024-12-13 23:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpioneer', '0003_remove_productcard_image_url_productcard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productcard',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
